name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-id=$RANDOM" >> $GITHUB_OUTPUT
      shell: bash  
    - run: |
        env
        chmod u+x ${{ github.action_path }}/goodbye.sh
        ${{ github.action_path }}/goodbye.sh
      shell: bash
